# Generated by Django 5.0.1 on 2024-02-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('crdthr', models.IntegerField()),
            ],
        ),
    ]
